name: Build API Documentation
run-name: Build the static html files for API documenation.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build sphinx html output
        run: sphinx-build -b html src/ build/
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-doc-html
          path: build/
