name: Sync approved PRs to internal codebase
on:
  pull_request_target:
    types: [labeled]

jobs:
  sync_prs_to_internal_codebase:
    name: GitHub PR to Internal Codebase Sync
    runs-on: ubuntu-latest
    if: github.event.label.name == 'PR-Sync-Merge'
    steps:
      - uses: actions/checkout@v4
      - name: Sync approved PRs to internal codebase
        uses: keninkujovic/gitlab-sync@2.1.0
        with:
          gitlab_url: ${{ secrets.GITLAB_URL }}
          gitlab_pat: ${{ secrets.GITLAB_TOKEN }}
          username: ${{ secrets.GIT_CONFIG_NAME }}
